### ISSUE TITLE
Weird Issue with Photoview/Photoprism

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/photoprism_ynh#14]
I used to have Photoview on `photos.domain.tld`. I saw photoprisim was available, so I uninstalled photoview and installed photoprism at  `photos.domain.tld/prisim`. I went to access it but it just goes to a page saying "Page not found"

However when I go to `photos.domain.tld`.  I get the photoview login:

![image](https://user-images.githubusercontent.com/73113656/176996559-ab93837b-a202-484d-b53b-049ef406d273.png)

Here's the uninstall log: https://paste.yunohost.org/raw/viyavemunu

Install log: https://paste.yunohost.org/raw/omuqopodos 

any thoughts?

**Comment by brimwats** [comment]
This was resolved by changing the root domain in application settings to photos.domain.tld and removing anything after the /

not sure what happened, leaving open but feel free to close

**Comment by Limezy** [comment]
It's clearly a cache issue with your browser.
Unless you have other comments I'll close that issue, and maybe add a line in the disclaimer saying that you should clear your browser cache if there was another app previously installed before (but that's pretty much the case for any Yunohost app you would install...)

**Comment by brimwats** [comment]
it wasn't quite, because it persisted on multiple devices / networks and after force reloads. I'm able to reproduce it (did it twice), but it's unlikely that anyone else will hit this.. closing
