### ISSUE TITLE
Uninstalling Photoprism breaks Webadmin App View

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/photoprism_ynh#15]
Hello!

Duplicated here: https://forum.yunohost.org/t/uninstalling-photoprism-removed-application-view/20296

My YunoHost server
Hardware: Dell R720
YunoHost version: 11.0.7 (testing).
I have access to my server : SSH, direct access
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : not really. I have a RAID server, where `/home` = ~2TB and `/var` = 20TB so most of my storage needs to be on /var

Hello!

I made a mistake when I configured my Photoprisim to use `/var/Multimedia/Pictures` for its library but also had its cache in `/var/Multimedia/Pictures/photoprism/cache`. Basically it just reindexed itself forever. I've now made a `/var/Multimedia/Other/photoprism/cache` folder, and then I deleted Photoprism and all of the files I could find related to it in /home and /var.  

The uninstall had an error: https://paste.yunohost.org/raw/sugujegaye

I went to reinstall photoprism and also ran into a similar error: https://paste.yunohost.org/raw/epitexeqon

It may be worth saying: I initally installed Photoprism on photos.maindomain.tld/prism but had to move it to photos.maindomain.tld becuase I kept getting the login page for the old app that was installed at that domain (photoview)

Application view also goes blank
![image](https://user-images.githubusercontent.com/73113656/177305851-d803a80f-1fe2-4ef5-bd44-45bbd80b959d.png)

**Comment by Limezy** [comment]
Hi, sorry I didn't have any time to follow-up Photoprism app these days.
Do you still have this problem ?
If not, have you found the root cause ?

**Comment by brimwats** [comment]
I had to basically find all photoprism config files and delete them, do a few reboots, clean up cache and reinstall everything and leaving photoprism storage outside of config. that works and photoprism is working these days
