### ISSUE TITLE
Location of files unclear

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/photoprism_ynh#16]
/var/www/photoprism/ seems to contain no photos.

It is essential to know the location of the files for at least two reasons: 
- Managing backups of your photo library
- It is a common good practice to keep software on faster/smaller SSD drives, and data on HDD. Many users might want to move their photo libraries away from SSD. 

I suggest to put info about data location on readme.

**Comment by tituspijean** [comment]
Agreed. However, a quick search in the code returns this:

https://github.com/YunoHost-Apps/photoprism_ynh/blob/4de2ab27722b2300a6faff4f910ecf5b93160cb6/scripts/install#L142

**Comment by cloo** [comment]
Thanks! Apparently data dir is here:
/home/yunohost.app/photoprism/photos/

**Comment by Limezy** [comment]
> Thanks! Apparently data dir is here:
/home/yunohost.app/photoprism/photos/

Yes you are right. The `/home/yunohost.app` is a very standard location for Yunohost apps (see Nextcloud for instance), this is why I haven't put any information on the readme. I'm gonna change that if you feel it's important.

**Comment by Limezy** [comment]
https://github.com/YunoHost-Apps/photoprism_ynh/blob/abf1681b1dc0517d2269cac6739652e249560be4/README.md?plain=1#L47

Solved !
