### ISSUE TITLE
Failed to execute command: Exec format error

### ISSUE THREAD

**Issue by centralscrutinizer21** [YunoHost-Apps/photoprism_ynh#18]
After successful installation service fails to start

- Hardware: Raspberry Pi 4 at home 4gb ram 6gb swap
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin
- Using, or trying to install package version/branch: testing

Log: https://paste.yunohost.org/gexajeqemo

**Comment by tituspijean** [comment]
Can you share your installation log?
It looks like the `amd64` architecture is downloaded by default.

**Comment by centralscrutinizer21** [comment]
Yes, her is the installation log https://paste.yunohost.org/raw/daxoxuxilo
I forgot to mention that I have an aarch64 raspbian installation as base for my yunohost setup

**Comment by navanchauhan** [comment]
@centralscrutinizer21 try to install now. Looks like the maintainer merged the fix for arm64

**Comment by centralscrutinizer21** [comment]
@navanchauhan 
Installation went ok with the arch branch, now after uploading some files for testing, all the functions seems to work. Only issue with the sharing feature as I mentioned in the matrix chat
