### ISSUE TITLE
initrd.img error, bad gateway but service running

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/photoprism_ynh#22]
### Describe the bug

I am facing a "502 Bad Gateway" error despite the service running.
The only error in the log is `template: initrd.img:216: bad character U+FFFD '�'`.

### Context

- Hardware: VPS amd64 (OVH 1vCPU, 2GB RAM, 2GB swap)
- YunoHost version: 11.0.9.5 and 11.0.9.9
- I have access to my server: SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2022.07.30~ynh1

### Logs

https://paste.yunohost.org/ipuresuyuw

Ignore the last line (it was me circumventing the systemd helper waiting for that keyword).

**Comment by Limezy** [comment]
Could you please try to update to 2022.07.30~ynh2 ?

**Comment by tituspijean** [comment]
Same thing, unfortunately: https://paste.yunohost.org/ekufahetar.pl

**Comment by Limezy** [comment]
Worst thing is that I had the same issue, I solved it, and I don't remember how 🤣

**Comment by Limezy** [comment]
Could you give me hints to reproduce ? 
Have you tried to upgrade, or just directly install 2022.07.30~ynh1 ?
Are you on a OVH VPS 1vcore 2GB ?

**Comment by tituspijean** [comment]
Since the initial install failed, I could only try to install version 2022.07.30~ynh1 and then 2022.07.30~ynh2.
Yes, that's my VPS. 😉

**Comment by tituspijean** [comment]
I'm actually on v11.0.9.9 since last night (I forgot to mention that earlier) and already have a 2GB swapfile. 😓

**Comment by Limezy** [comment]
What about if you launch manually the exec instead of doing it through the yunohost service ?
```
sudo yunohost service stop photoprism
sudo /var/www/photoprism/live/bin/photoprism --trace start
```
And then check the URL ? (this will launch photoprism with default template)

**Comment by Limezy** [comment]
Oh, I think I got it. The datadir, where lies the template (which seem to have a problem), is not removed by default.
So it may have been corrupted by a former version (2022.07.30~ynh1 or before) ?
Could you please uninstall using the purge option, and then retry installing 2022.07.30~ynh2 ?

**Comment by tituspijean** [comment]
Same error after purging the app. :(

**Comment by Limezy** [comment]
Crazy stuff !
Why is it working for me with the same hardware and the same Yunohost 🤔 
I'll maybe try to install from a fresh Yunohost again

**Comment by Limezy** [comment]
I have tried installing photoprism on an old 11.0.7 snapshot I had from June (after updating to 11.0.9.9).
Installation went through **and I couldn't reproduce the issue** ! 😦 
Let me try on a 4.3.6.2 snapshot I have from Feb... before and after the update... 

Could it have any relationship with this ? https://forum.yunohost.org/t/migration-to-v11-failed-because-of-boot-has-less-than-70mb-available/20823 
The more I try to remember the more I'm convinced that I did solve that issue only by updating to a newer version of Yunohost

**Comment by Limezy** [comment]
OK, great news **I was able to reproduce** on yunohost 4.3.6.2 (using that branch https://github.com/Limezy/photoprism_ynh/tree/check-issue to deactivate the debian 11 minimum requirement)

So things seem to indicate that this issue is related to older versions.
Now I have to find out what happens if I upgrade my 4.3.6.2 and why that issue doesn't happen on fresher installs

**Comment by Limezy** [comment]
OK, I think I'm pretty close now.
I have removed `initrd.img`, `initrd.img.old`, `vmlinuz` and `vmlinuz.old` from the root directory, restarted photoprism, and now it works !
Of course this is not a solution. But it looks like some parameter is not given well to photoprism, which probably defaults to the root as a base folder and has troubles when viewing these files...

**Comment by Limezy** [comment]
@tituspijean je sèche ! Any idea ?
I've tried to config all the paths, including optional paths, and still that bug.
I don't understand why it would work or not, and why photoprism executable would look at these files on the root...

**Comment by Limezy** [comment]
As a small step forward @tituspijean : I have just launched a new OVH VPS test instance, from OVH's Debian 11 image.
The photoprism app is working perfectly right away !
* There are no initrd.img files at the root
* The `dpkg -l linux* | grep -E '^ii.*-(headers|image)'` command returns : 
```
ii  linux-image-4.19.0-18-cloud-amd64          4.19.208-1   amd64        Linux 4.19 for x86-64 cloud (signed)
ii  linux-image-4.19.0-21-cloud-amd64          4.19.249-2   amd64        Linux 4.19 for x86-64 cloud (signed)
ii  linux-image-5.10.0-17-cloud-amd64          5.10.136-1   amd64        Linux 5.10 for x86-64 cloud (signed)
ii  linux-image-cloud-amd64                    5.10.136-1   amd64        Linux for x86-64 cloud (meta-package)
```

On my previous instance (former Debian 10, upgraded to Debian 11 through Yunohost migration
* There were initrd.img files at the root
* The `dpkg -l linux* | grep -E '^ii.*-(headers|image)'` command returned : 
```
ii  linux-image-5.10.0-16-cloud-amd64          5.10.127-2   amd64        Linux 5.10 for x86-64 cloud (signed)
ii  linux-image-5.10.0-17-cloud-amd64          5.10.136-1   amd64        Linux 5.10 for x86-64 cloud (signed)
ii  linux-image-cloud-amd64                    5.10.136-1   amd64        Linux for x86-64 cloud (meta-package)
```

**Comment by Limezy** [comment]
OK, another step forward : I have launched again an old Yunohost based on Debian 10, then migrated it to Debian 11.
The command `uname -r` returns `4.19.0-18-cloud-amd64`, so even though the 5.10 kernel is present, **it is not used**.
After a reboot, the same command `uname -r` then returns `5.10.0-17-cloud-amd64`
As a side question, shouldn't Yunohost migration include a reboot in the process to load the latest kernel ?
Let me now check what happens with Photoprism

**Comment by Limezy** [comment]
After some testing, here is my conclusion : 
* Photoprism won't run if there is any of the `initrd.img`, `initrd.img.old`, `vmlinuz`, `vmlinuz.old` symlinks at the root
* Photoprism will run no matter what kernel is loaded, provided these symlinks are removed

Apparently : 
* A fresh yunohost (4.3.x or 11.0.x) doesn't have these symlinks
* A yunohost that went through the 11.0.x migration will have these symlinks
* These symlinks are completely safe to remove

How to fix the bug : 
* The very very ugly way : tell users in the disclaimer that they should run commands like `sudo su`, `cd /`, `rm initrd.img initrd.img.old vmlinuz vmlinuz.old` to have photoprism running
* The very very ugly way : have the install script doing it for them... (I'm not sure this would be allowed anyway...)
* The nice way : find why that photoprism executable would want to read inside symlinks placed at the root directory...

**Comment by Limezy** [comment]
OK, I have found a nice way to fix that bug.
The idea is to use some systemd tricks to sandbox the service and prevent photoprism executable from seing anything in the root directory. I have used the `TemporaryFileSystem=/:ro` parameter to have all the filesystem looking like invisible, and then used `BindReadOnlyPaths=` and `BindPaths=` to put back as visible some targeted directories needed by photoprism.
My current PR could be more elegant as I've basically put everything back for now, but it works.
@tituspijean would you mind testing an upgrade to my branch ? Thanks !

**Comment by Limezy** [comment]
Checked on a few prod servers already. Merging to main.

**Comment by tituspijean** [comment]
Sorry I could not test it last night, I had issues with my RPi at home and focused on that. I will test this within 2 days. :)
Nice idea to use the systemd safety flags to contain it!

**Comment by Limezy** [comment]
Take your time, meanwhile I'm packaging Immich 🤣

**Comment by tituspijean** [comment]
Confirmed to be working! 🎉
