### ISSUE TITLE
Update to latest Version

### ISSUE THREAD

**Issue by Delegator9176** [YunoHost-Apps/photoprism_ynh#37]
I saw upstream that we are a little bit behind. The latest updates also contained some security improvements so I would be very happy if someone would like to take care?

https://github.com/photoprism/photoprism/releases/tag/230625-17242fb07

Thanks in advance

**Comment by Thovi98** [comment]
Thanks for your issue!
Indeed, I expercienced some troubles to update to the latest version of Photoprism on Yunohost. You will have to wait for now until Yunohost supports Bookworm (or I find another way to go).

**Comment by pirboazo** [comment]
Hi 
If you have need person to test . I have time for that.
I have installed yunohost 12.
how i can help ?


I

**Comment by Thovi98** [comment]
Thanks for your help offer! If you want to test, the following branch must work (althought I will probably refactor it a bit to ditch the docker extraction and use proper builds).

`yunohost app install https://github.com/Thovi98/photoprism_ynh/tree/upgrade-for-bookworm --debug`

**Comment by Thovi98** [comment]
Or better, use this branch without the docker-extraction but with proper builds:

`yunohost app install https://github.com/Thovi98/photoprism_ynh/tree/official_builds --debug`

**Comment by xplosionmind** [comment]
Hey @Thovi98! I was finally able to install Photoprism using the last command you sent. It looks ok! [Here](https://paste.yunohost.org/raw/uhuzidoyuh) is the log!

**Comment by Thovi98** [comment]
Thanks @xplosionmind for your feadback!
I will try to update soon.

As you are on Bookworm, is it a test server?

**Comment by xplosionmind** [comment]
> As you are on Bookworm, is it a test server?

Yep! Not prod.

**Comment by Thovi98** [comment]
@xplosionmind Could you please try an update?

And if you don’t mind, I would be glad to know if now the upgrade from actual master to my branch is working 😇

**Comment by xplosionmind** [comment]
Sorry could you type out for me the terminal command I should run? I don’t know how to run an upgrade from a different branch/repo

**Comment by Thovi98** [comment]
Yes of course, thanks!
It would first be to uninstall photoprism (new version will be able to be multi_instances normally 🤞).

Then just install photoprism like you would do for any app (`yunohost app install photoprism`).

Finally upgrade the app with `yunohost app install https://github.com/Thovi98/photoprism_ynh/tree/official_builds --debug` and see if you can still login and average features works.

**Comment by xplosionmind** [comment]
Thanks for the help, @Thovi98!

I uninstalled photoprism, then I installed it normally (it seems to be working well), and lastly I run `yunohost app upgrade app photoprism -u https://github.com/Thovi98/photoprism_ynh/tree/official_builds --debug`—I substituted `install` with `upgrade app photoprism -u`, because It would not work otherwise.

The last upgrade command failed, see the logs [here](https://paste.yunohost.org/raw/atuteletub)

**Comment by xplosionmind** [comment]
TBH, I have no idea… How can I help you debug it?
If you want, you can send me your SSH key and I can give you access, since it is a clean server I use for testing only.

**Comment by Thovi98** [comment]
Thanks for your offer!
I’ve updated my instance to bookworm so I could debug. I could successfully update thanks to latest commit. Don’t hesitate to try :)

**Comment by xplosionmind** [comment]
Hi @Thovi98! Sorry for the late reply. Should I install PhotoPrism normally from the web interface and then update from your repo? Give me instructions and I will follow them.

Thanks a lot for your efforts!

**Comment by Thovi98** [comment]
Sorry, I forgot to reply.
You may now want to try the upgrade with the testing branch, by
`sudo yunohost app upgrade photoprism -u https://github.com/YunoHost-Apps/photoprism_ynh/tree/testing --debug`
